### ISSUE TITLE
import ncar_jobqueue fails on non-NCAR HPC

### ISSUE THREAD

**Issue by klindsay28** [NCAR/ncar-jobqueue#24]
I have some analysis notebooks that cache the result of computations and use the cached values if they are available. If the cached results are not available dask/xarray computations on done, using a cluster instantiated with ncar_jobqueue. If the cached results are available, the computations in the notebooks are lightweight and don't need HPC resources. I attempted to run one of these notebooks on my laptop, with cached results available, and got the following error on `import ncar_jobqueue`:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/klindsay/miniconda3/envs/CESM2_coup_carb_cycle_JAMES/lib/python3.7/site-packages/ncar_jobqueue/__init__.py", line 5, in <module>
    from . import config
  File "/Users/klindsay/miniconda3/envs/CESM2_coup_carb_cycle_JAMES/lib/python3.7/site-packages/ncar_jobqueue/config.py", line 111, in <module>
    data = _generate_config(config_data_file_path, template_file_path)
  File "/Users/klindsay/miniconda3/envs/CESM2_coup_carb_cycle_JAMES/lib/python3.7/site-packages/ncar_jobqueue/config.py", line 77, in _generate_config
    host = identify_host()
  File "/Users/klindsay/miniconda3/envs/CESM2_coup_carb_cycle_JAMES/lib/python3.7/site-packages/ncar_jobqueue/util.py", line 36, in identify_host
    raise exc
  File "/Users/klindsay/miniconda3/envs/CESM2_coup_carb_cycle_JAMES/lib/python3.7/site-packages/ncar_jobqueue/util.py", line 33, in identify_host
    raise RuntimeError(message)
RuntimeError: Unable to determine which NCAR cluster you are running on...
	Supported machines include: cheyenne, casper/dav, hobart.
```

I would like to be able to distribute my scripts with cached results to enable reproducibility away from NCAR HPC machines. This error appears to hinder that. Any suggestions on how to run these notebooks on non-NCAR HPC machines when the cached results are available?

One idea is to put the `import ncar_jobqueue` statement into a try block and pass on `RuntimeError`. I'm not sure if there is a better approach than this, if the workaround is in my code.

Alternatively, I wonder if `ncar_jobqueue` could be enhanced in some way to avoid raising `RuntimeError` on `import ncar_jobqueue` on non-NCAR HPC machines.

**Comment by andersy005** [comment]
@klindsay28, I have a PR in #25 to address this. With #25, when ncar-jobqueue is unable to detect which NCAR machine the user is running on, it will warn the user that it is going to use `LocalCluster` instead of one of `SLURMCluster`, `PBSCluster`....

**Comment by klindsay28** [comment]
Thanks @andersy005. I think that will work in my workflow. I'll give #25 a try, but I'm in CESM working group meetings for the next few days, so my testing might not occur immediately.

**Comment by andersy005** [comment]
Closing this issue for the time being. In case #25 didn't fully address this issue, feel free to re-open.
